import Footer from "@/components/Footer \u001A";
import './../globals.css'
import SearchHeader from "@/components/SearchHeader \u001A";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SearchLayout({ children }) {
  return (
    <div >
       
        <SearchHeader />
        {children}
       
    </div>
  );
}
